apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Shopizer
  description: Shopizer application
  annotations:
    github.com/project-slug: GitHubDevOpsDemo/Shopizer
spec:
  type: Service
  lifecycle: development
  owner: DevOpsTeam
