# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2   
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  publish-job:
      runs-on: ubuntu-latest
      #defaults:
        #run:
          #shell: bash
          #working-directory: build
      needs: [build]
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - uses: actions/cache@v1
          with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-m2   
        #- run: pwd
        #- run: ls -lart
        #- run: mvn -B package --file /build/pom.xml -DskipTests
        - run: mvn -B package --file ${GITHUB_WORKSPACE}/pom.xml -DskipTests
        - run: mkdir staging && cp ${GITHUB_WORKSPACE}/sm-shop/target/*.war staging
        - uses: actions/upload-artifact@v1
          with:
            name: Shopizer-Package
            path: staging

  containerize_n_push_to_registry:
    name: Build Docker image and push to GitHub Container Registry
    runs-on: ubuntu-latest
    needs: [build, publish-job]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Download built artifact
        #uses: actions/download-artifact@master
        uses: actions/download-artifact@v1
        with:
          name: Shopizer-Package
          #path: staging
      - name: Move the artifact to target
        run: |
          pwd
          ls -lart
          mkdir -p {GITHUB_WORKSPACE}/sm-shop/target
          mv artifact/ROOT.war {GITHUB_WORKSPACE}/sm-shop/target
          #docker build -t de.rieckpil.blog/github-actions-sample github-actions-java-maven  
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.CR_Username }}
          password: ${{ secrets.CR_Password }}
          registry: ghcr.io
          repository: githubteamuser2/shopizer
          tags: ${{ github.sha }}
          dockerfile: ${GITHUB_WORKSPACE}/sm-shop/Dockerfile
