# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
   Run-Test-Automation:
      name: Run automated Test from Integration_test reporsitory on Saucelabs
      runs-on: ubuntu-latest
      #needs: [Deploy]
      steps :
       - name: Repository Dispatch
         #run: curl -X POST -u "${{ secrets.ACCESS_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/GitHubDevOpsDemo/Shopizer/dispatches --data '{"event_type": "invoke_test"}'
         run: |
           curl \
             -X POST \
             https://api.github.com/repos/GitHubDevOpsDemo/Shopizer/dispatches \
             -H "Accept: application/vnd.github.v3+json" \
             -H "Content-Type: application/json" \
             -u ${{ secrets.ACCESS_TOKEN }} \
             --data '{"event_type": "invoke_test", "client_payload": { "repository": "'"https://github.com/GitHubDevOpsDemo/cima-integration-test"'" }}'
##             https://api.github.com/repos/githubteamsuser1/cima-integration-test/dispatches \
#             --data '{"event_type":"invoke-test"}'
