# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
        
  Run-Test-Automation:
      name: Run Test Automation
      runs-on: ubuntu-latest
  #    needs: [secret-scan]
      steps:
        - name: Repository Dispatch
          uses: peter-evans/repository-dispatch@v1
          with:
            #token: ${{ secrets.TEST_ACCESS_TOKEN }}
            token: ${{ secrets.ACCESS_TOKEN }}
            repository: "GitHubDevOpsDemo/cima-integration-test"
            event-type: invoke_test
            #client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
    
  Run-Performance:
    name: Invoke Performance Test 
    runs-on: ubuntu-latest
    #needs: [secret-scan, analyze, analyze_dockerfile, build, publish-job, containerize_n_push_to_registry, scan-image, Provision-env, Deploy, Run-Test-Automation]
    #needs: [secret-scan, Run-Test-Automation]
    steps:
      - name: Invoke Performance Test
        uses: actions/checkout@v2
