# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
#To display the triggering of the pipeline on commit
name: Java CI with Maven

on:
  push:
    branches: '*'
  pull_request:
    branches: [ master ]
  repository_dispatch:
    types: [invoke_build_deploy]
env:
  GITHUB_RUN_ID: ${{secrets.GITHUB_RUN_ID}}
  GITHUB_RUN_NUMBER: ${{secrets.GITHUB_RUN_NUMBER}}



jobs:

  #transition-issue:
  #  name: Transition Issue
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: Login
  #    uses: atlassian/gajira-login@v3
  #    env:
  #      JIRA_BASE_URL: "https://bluice.atlassian.net/" #${{ secrets.JIRA_BASE_URL }}
  #      JIRA_USER_EMAIL: "sen.arindam@pwc.com" #${{ secrets.JIRA_USER_EMAIL }}
  #      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}  
  #  - name: Transition issue
  #    uses: atlassian/gajira-transition@v3
  #    with:
  #      issue: BLUIC-4
  #      transition: "In progress"

  extract-issue-id:
     name: Extract Issue Id
     #runs-on: ['self-hosted', 'Windows', 'X64']
     runs-on: ubuntu-latest
     steps:
     - name: set-issue-id
       shell: bash
       run: |
         set commit-msg: ${{ github.event.head_commit.message }}
         echo $commit-msg
     - name: Parse Jira Keys from Commit
       id: jira_keys
       if: always()
       uses: HighwayThree/jira-extract-issue-keys@master
       with:
         #is-pull-request: ${{ github.event_name == 'pull_request' }}
         parse-all-commits: ${{ github.event_name == 'push' }}
         commit-message: "BLUIC-5 <message>"
#     - name: echo  
#       run: |
#         echo "Commit message: ${{ steps.jira_keys }}
     - name: Push Build Info to Jira
       if: steps.jira_keys.outputs.jira-keys != ''
       id: push_build_info_to_jira
       uses: HighwayThree/jira-upload-build-info@master
       with:
         #cloud-id: '${{ secrets.CLOUD_ID }}'
         client-id: '${{ secrets.JIRA_GH_CLIENT_ID }}'
         client-secret: '${{ secrets.JIRA_GH_CLIENT_SECRET }}'
         cloud-instance-base-url: "https://bluice.atlassian.net/"
         pipeline-id: '${{ github.repository }} ${{ github.workflow }}'
         build-number: ${{ github.run_number }}
         build-display-name: 'Workflow: ${{ github.workflow }} (#${{ github.run_number }})'
         build-state: "${{ env.BUILD_STATE }}"
         build-url: '${{github.event.repository.url}}/actions/runs/${{github.run_id}}'
         update-sequence-number: '${{ github.run_id }}'
         last-updated: '${{github.event.head_commit.timestamp}}'
         issue-keys: "${{ steps.jira_keys.outputs.jira-keys }}"
         commit-id: '${{ github.sha }}'
         repo-url: '${{ github.event.repository.url }}'
         build-ref-url: '${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}'
     - name: Confirm Jira Build Output
       if: success()
       run: |
         echo "Jira Upload Build Info response: ${{ steps.push_build_info_to_jira.outputs.response }}" #
        

#  secret-scan:
#    name: Repo Secret Scan 
#    #runs-on: [self-hosted, 'Windows', 'X64']
#    runs-on: ubuntu-latest
#    continue-on-error: true
#    steps:
#      - uses: actions/checkout@v2
#      - uses: max/secret-scan@master
#      
#  analyze:
#     name: Analyze Source Code
#     #runs-on: ['self-hosted', 'Windows', 'X64']
#     runs-on: ubuntu-latest
#     needs: [secret-scan]
#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2#

 

#  comment:
#    name: comments
#    runs-on: ubuntu-latest
#    needs: [analyze]
#    steps:
#    #env:
#      #GITHUB_RUN_ID: ${{secrets.GITHUB_RUN_ID}}
#      #GITHUB_RUN_NUMBER: ${{secrets.GITHUB_RUN_NUMBER}}
#    - name: Parse Jira Keys from Commit
#      id: jira_keys
#      if: always()
#      uses: HighwayThree/jira-extract-issue-keys@master
#      with:
#        #is-pull-request: ${{ github.event_name == 'pull_request' }}
#        parse-all-commits: ${{ github.event_name == 'push' }}
#    - name: set
#      shell: bash
#      run: |
#        echo "BUILD_STATE=successful" >> $GITHUB_ENV
#      #env:
#        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#    - name: Push Build Info to Jira
#      if: steps.jira_keys.outputs.jira-keys != ''
#      id: push_build_info_to_jira
#      uses: HighwayThree/jira-upload-build-info@master
#      with:
#        #cloud-id: '${{ secrets.CLOUD_ID }}'
#        client-id: '${{ secrets.JIRA_GH_CLIENT_ID }}'
#        client-secret: '${{ secrets.JIRA_GH_CLIENT_SECRET }}'
#        cloud-instance-base-url: "https://bluice.atlassian.net/"
#        pipeline-id: '${{ github.repository }} ${{ github.workflow }}'
#        build-number: ${{ github.run_number }}
#        build-display-name: 'Workflow: ${{ github.workflow }} (#${{ github.run_number }})'
#        build-state: "${{ env.BUILD_STATE }}"
#        build-url: '${{github.event.repository.url}}/actions/runs/${{github.run_id}}'
#        update-sequence-number: '${{ github.run_id }}'
#        last-updated: '${{github.event.head_commit.timestamp}}'
#        issue-keys: "${{ steps.jira_keys.outputs.jira-keys }}"
#        commit-id: '${{ github.sha }}'
#        repo-url: '${{ github.event.repository.url }}'
#        build-ref-url: '${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}'
#    - name: Confirm Jira Build Output
#      if: success()
#      run: |
#        echo "Jira Upload Build Info response: ${{ steps.push_build_info_to_jira.outputs.response }}" #




        
      
 
